name: Custom Kernel Builder (The Brickmaker 9000)

on:
  workflow_dispatch: # Canın ne zaman sıkılırsa butona basıp başlat diye

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Çek
      uses: actions/checkout@v4

    - name: Ortamı Hazırla (Savaş Alanı)
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential libncurses5-dev libssl-dev bison flex libelf-dev clang lld llvm

    - name: Toolchain İndir (Clang/GCC)
      run: |
       mkdir -p $GITHUB_WORKSPACE/toolchain
        cd $GITHUB_WORKSPACE/toolchain
        # GitHub üzerinde barındırılan, wget ile sorunsuz inen stabil Android Clang 17 derleyicisi
        wget https://github.com/ZyCromerZ/Clang/releases/download/17.0.6-20240217-release/Clang-17.0.6-20240217-release.tar.gz
        tar -xf Clang-17.0.6-20240217-release.tar.gz
        rm Clang-17.0.6-20240217-release.tar.gz
        echo "$GITHUB_WORKSPACE/toolchain/bin" >> $GITHUB_PATH

    - name: KernelSU Entegre Et (Rootsuz Yaşayamayanlar İçin)
      run: |
        # Kernel kaynak kodunun içine KernelSU'yu enjekte ediyoruz
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

    - name: Overclock Ayarları (Cihazı Eritme Aşaması)
      run: |
        echo "Repodaki tüm dts ve dtsi dosyalarında frekans operasyonu başlıyor..."
        find arch/arm64/boot/dts/ -name "*.dts*" -type f -exec sed -i 's/opp-hz = \/bits\/ 64 <[0-9]*>/opp-hz = \/bits\/ 64 <2300000000>/g' {} +
        find arch/arm64/boot/dts/ -name "*.dts*" -type f -exec sed -i 's/gpu_freq = <[0-9]*>/gpu_freq = <900000000>/g' {} +
        echo "GitHub Actions ameleliği tamamladı, frekanslar zorla yazıldı!""

    - name: Derleme Zamanı
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        # Varsa Clang ayarların:
        # export CC=clang

        make <arch/arm64/configs/gta7litewifi_defconfig>
        make -j$(nproc)

    - name: Artefaktı Paketle ve Fırlat
      uses: actions/upload-artifact@v4
      with:
        name: Overclocked-KernelSU-Kernel
        path: arch/arm64/boot/Image.gz-dtb # Veya cihazın hangi formatı yiyorsa
